"  <!DOCTYPE html>\n"
"  <html lang='en'>\n"
"  <head>\n"
"  <meta charset='utf-8'>\n"
"  <title>baby-trum</title>\n"
"  <style> .center{ width:480px; margin: 0 auto; } progress{ height:30px;} button {width:5em; height:2em;}</style>\n"
"  </head>\n"
"  <body>\n"
"   <div class='center'>\n"
"  <h2>baby trum</h2>\n"
"   <table cellpadding='1' >\n"
"    <tr>\n"
"      <td> <a href='/'><button type='button' onclick=set_value('run',1)> <b>START</b> </button></a></td>\n"
"      <td> <a href='/'><button type='button' onclick=set_value('run',0)> <b>STOP</b> </button></a></td>\n"
"      <td><p id='run'><b><font size='5'> STOP </font></b></p></td>\n"
"    </tr>\n"
"    <tr>\n"
"      <td> <a href='/'><button type='button' onclick=set_value('power',-5)> <b>－</b> </button></a></td>\n"
"      <td> <a href='/'><button type='button' onclick=set_value('power',5)>  <b>＋</b> </button></a></td>\n"
"      <td> <progress id='power_progress' value='55' min='0' max='100'></progress></td>\n"
"      <td><p id='power_value'><b><font size='5'> power 55% </font></b></p></td>\n"
"    </tr>\n"
"  </table>\n"
"  </div>\n"
"  </body>\n"
"  <script language='javascript' type='text/javascript'>\n"
"  function set_value(item, value) {\n"
"    var request = new XMLHttpRequest();\n"
"    request.open('GET', '/api?item=' + item + '&value=' + value , true);\n"
"    request.responseType = 'json';\n"
"    request.onload = function () {\n"
"            let data = this.response;\n"
"            let result = data.result;\n"
"            let item = data.item;\n"
"            let value = data.value;\n"
"            if (result!='OK') {\n"
"                alert('ERROR');\n"
"            } else if (item=='run') {\n"
"                document.getElementById('run').innerHTML = value;\n"
"            } else if (item=='power') {\n"
"                document.getElementById('power_progress').value = value;\n"
"                document.getElementById('power_value').innerHTML = 'power ' + value + '%';\n"
"            }\n"
"        };\n"
"    request.onerror = function () {\n"
"      alert('ERROR');\n"
"    };\n"
"    request.send();\n"
"  }\n"
"  </script>\n"
