"  <!DOCTYPE html>\n"
"  <html lang='en'>\n"
"  <head>\n"
"    <meta charset='utf-8'>\n"
"    <title>baby-trum</title>\n"
"    <style>\n"
"      .center{ width:480px; margin: 0 auto; }\n"
"      progress{ width:125px; height:30px;}\n"
"      button {width:60px; height:30px;\n"
"      border:none; color:#FFF;\n"
"      background:#0d6efd; border-radius:5px;}\n"
"      p{height:2em; margin-block-start:0px; margin-block-end:0px;}\n"
"    </style>\n"
"  </head>\n"
"  <body>\n"
"    <div class='center'>\n"
"      <h2>baby trum</h2>\n"
"      <p><nobr>\n"
"        <button type='button' onclick=set_value('run',1)> <b>RUN</b> </button>\n"
"        <button type='button' onclick=set_value('run',0)> <b>STOP</b> </button>\n"
"      </nobr></p>\n"
"      <b><font size='5'><a id='run'> STOP </a></font></b>\n"
"      <hr>\n"
"      <p><nobr>\n"
"        <button type='button' onclick=set_value('power',-5)> <b>－</b> </button>\n"
"        <button type='button' onclick=set_value('power',5)>  <b>＋</b> </button>\n"
"      </nobr></p>\n"
"      <b><font size='5'><a id='power_value'> POW:0% </a></font></b>\n"
"      <p>\n"
"        <progress id='power_progress' value='0' min='0' max='100'>0</progress>\n"
"      </p>\n"
"  </div>\n"
"  </body>\n"
"  <script language='javascript' type='text/javascript'>\n"
"  function set_value(item, value) {\n"
"    var request = new XMLHttpRequest();\n"
"    request.open('GET', '/api?item=' + item + '&value=' + value , true);\n"
"    request.responseType = 'json';\n"
"    request.onload = function () {\n"
"            let data = this.response;\n"
"            let result = data.result;\n"
"            let item = data.item;\n"
"            let value = data.value;\n"
"            if (result!='OK') {\n"
"                alert('ERROR');\n"
"            } else if (item=='run') {\n"
"                document.getElementById('run').textContent = value;\n"
"            } else if (item=='power') {\n"
"                document.getElementById('power_progress').value = value;\n"
"                document.getElementById('power_value').textContent = 'POW:' + value + '%';\n"
"            }\n"
"        };\n"
"    request.onerror = function () {\n"
"      alert('ERROR');\n"
"    };\n"
"    request.send();\n"
"  }\n"
"  </script>\n"
