"<!DOCTYPE html>\n"
"<html lang='en'>\n"
"<head>\n"
"<meta charset='utf-8'>\n"
"<title>baby-tram magma</title>\n"
"<style>\n"
".center{ width:480px; margin: 0 auto; }\n"
"progress{ width:125px; height:30px;}\n"
"button {width:60px; height:30px;\n"
"border:none; color:#FFF;\n"
"background:#0d6efd; border-radius:5px;}\n"
"p{height:2em; margin-block-start:0px; margin-block-end:0px;}\n"
"select{width:60; height:30px;}\n"
"}\n"
"</style>\n"
"</head>\n"
"<body>\n"
"<div class='center'>\n"
"<h2>baby tram</h2>\n"
"<p><nobr>\n"
"<button type='button' onclick=run_start()> <b>RUN</b> </button>\n"
"<button type='button' onclick=run_stop()> <b>STOP</b> </button>\n"
"</nobr></p>\n"
"<b><font size='5'><a id='run'> STOP </a></font></b>\n"
"<hr>\n"
"<p><nobr>\n"
"<a>File No.</a>\n"
"<select id='filenumber'>\n"
"<option value=1>1</option> <option value=2>2</option> <option value=3>3</option> <option value=4>4</option> <option value=5>5</option>\n"
"<option value=6>6</option> <option value=7>7</option> <option value=8>8</option> <option value=9>9</option> <option value=10>10</option>\n"
"</select>\n"
"<button type='button' onclick=load_table()> <b>load</b> </button>\n"
"<button type='button' onclick=save_table()> <b>save</b> </button>\n"
"</nobr></p>\n"
"<br>\n"
"<p><nobr>\n"
"<a>Desc.</a>\n"
"<input type='text' id='description'size='24' />\n"
"</nobr></p>\n"
"<table border='1' style='border: 1px solid black; border-collapse: collapse;' id='table'>\n"
"<thead>\n"
"<tr bgcolor='#eeeeee'>\n"
"<td>color(r/g/b/y)</td>\n"
"<td>brake[ms]</td>\n"
"<td>power[%]</td>\n"
"<td>delete</td>\n"
"</tr>\n"
"</thead>\n"
"<tbody id='tbody'>\n"
"<tbody>\n"
"</table>\n"
"<a href='javascript:add_row(\"g\", 0, 50);'>add[+]</a>\n"
"</div>\n"
"</body>\n"
"<script language='javascript' type='text/javascript'>\n"
"function run_start() {\n"
"var request = new XMLHttpRequest();\n"
"request.open('POST', '/api/run/start', true);\n"
"request.responseType = 'json';\n"
"request.setRequestHeader('Content-Type', 'application/json');\n"
"request.onload = function () {\n"
"let data = this.response;\n"
"let result = data.result;\n"
"if (result!='OK') {\n"
"alert('ERROR');\n"
"} else {\n"
"document.getElementById('run').textContent = 'RUN';\n"
"}\n"
"};\n"
"request.onerror = function () {\n"
"alert('ERROR');\n"
"};\n"
"let rows = get_table_rows();\n"
"let data ={'table':rows};\n"
"let json_str = JSON.stringify(data);\n"
"request.send(json_str);\n"
"}\n"
"function run_stop() {\n"
"var request = new XMLHttpRequest();\n"
"request.open('GET', '/api/run/stop' , true);\n"
"request.responseType = 'json';\n"
"request.onload = function () {\n"
"let data = this.response;\n"
"let result = data.result;\n"
"if (result!='OK') {\n"
"alert('ERROR');\n"
"} else {\n"
"document.getElementById('run').textContent = 'STOP';\n"
"}\n"
"};\n"
"request.onerror = function () {\n"
"alert('ERROR');\n"
"};\n"
"request.send();\n"
"}\n"
"function get_table_rows() {\n"
"let tb = document.getElementById('tbody');\n"
"const col_limit = 3;\n"
"let rows = [];\n"
"for (let row of tb.rows) {\n"
"let cols = [];\n"
"let col_num = 0;\n"
"for(let cell of row.cells){\n"
"col_num += 1;\n"
"if (col_num <= col_limit) {\n"
"cols.push(cell.innerText);\n"
"}\n"
"//console.log(cell.innerText);\n"
"}\n"
"rows.push(cols);\n"
"}\n"
"//console.log(rows);\n"
"return rows;\n"
"}\n"
"function add_row(color, brake, poower) {\n"
"var tb = document.getElementById('tbody');\n"
"var tr = document.createElement('tr');\n"
"var init_values = [color, brake, poower];\n"
"var init_attr = ['center','right','right']\n"
"for (let i=0; i<3; i++) {\n"
"var td = document.createElement('td');\n"
"td.textContent = init_values[i];\n"
"td.setAttribute('contenteditable', 'true');\n"
"td.setAttribute('align', init_attr[i])\n"
"tr.appendChild(td);\n"
"}\n"
"var td = document.createElement('td');\n"
"td.innerHTML = '<a href=\"javascript:void(0);\">[x]</a>';\n"
"td.setAttribute('onclick', 'this.parentNode.outerHTML = \"\"');\n"
"td.setAttribute('align', 'center')\n"
"tr.appendChild(td);\n"
"tb.appendChild(tr);\n"
"}\n"
"function load_table() {\n"
"let filenumber = document.getElementById('filenumber').value;\n"
"var request = new XMLHttpRequest();\n"
"request.open('POST', '/api/table/load', true);\n"
"request.responseType = 'json';\n"
"request.setRequestHeader('Content-Type', 'application/json');\n"
"request.onload = function () {\n"
"let data = this.response;\n"
"let result = data.result;\n"
"let description = data.description;\n"
"let table = data.table;\n"
"let value = data.value;\n"
"if (result!='OK') {\n"
"alert('ERROR');\n"
"} else {\n"
"document.getElementById('description').value = description;\n"
"let tb = document.getElementById('tbody');\n"
"while (tb.rows.length > 0) tb.deleteRow(0);\n"
"for (let row of table) {\n"
"add_row(row[0], row[1], row[2]);\n"
"}\n"
"}\n"
"};\n"
"request.onerror = function () {\n"
"alert('ERROR');\n"
"};\n"
"let data ={'filenumber': filenumber};\n"
"let json_str = JSON.stringify(data);\n"
"request.send(json_str);\n"
"}\n"
"function save_table() {\n"
"let filenumber = document.getElementById('filenumber').value;\n"
"let description = document.getElementById('description').value;\n"
"if (false == window.confirm(filenumber + ':' + description + '\\n' + 'save ok ?')) {\n"
"return;\n"
"}\n"
"var request = new XMLHttpRequest();\n"
"request.open('POST', '/api/table/save', true);\n"
"request.responseType = 'json';\n"
"request.setRequestHeader('Content-Type', 'application/json');\n"
"request.onload = function () {\n"
"let data = this.response;\n"
"let result = data.result;\n"
"let item = data.item;\n"
"let value = data.value;\n"
"if (result!='OK') {\n"
"alert('ERROR');\n"
"} else if (item=='run') {\n"
"document.getElementById('run').textContent = value;\n"
"} else if (item=='power') {\n"
"document.getElementById('power_progress').value = value;\n"
"document.getElementById('power_value').textContent = 'POW:' + value + '%';\n"
"}\n"
"};\n"
"request.onerror = function () {\n"
"alert('ERROR');\n"
"};\n"
"let rows = get_table_rows();\n"
"let data ={'filenumber':filenumber, 'description': description, 'table':rows};\n"
"let json_str = JSON.stringify(data);\n"
"request.send(json_str);\n"
"}\n"
"</script>\n"
